version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
