🗃components:
  - changed-files:
      - any-glob-to-any-file:
        - src/lib/components/*
🧩types:
  - changed-files:
      - any-glob-to-any-file:
        - frontend/src/lib/types/*
⚒utils:
  - changed-files:
      - any-glob-to-any-file:
        - src/lib/utils/*
📄pages:
  - changed-files:
      - any-glob-to-any-file:
        - src/routes/*
        - src/app.html
        - src/error.html
🕵test:
  - changed-files:
      - any-glob-to-any-file:
        - tests/*
🗺config:
  - changed-files:
      - any-glob-to-any-file:
        - .env.example
        - .eslintignore
        - .eslintrc.cjs
        - .gitattributes
        - .gitignore
        - .npmrc
        - .prettierignore
        - .prettierrc
        - playwright-ct.config.ts
        - playwright.config.ts
        - postcss.config.cjs
        - svelte.config.js
        - tailwind.config.cjs
        - tsconfig.json
        - vite.config.ts
🎁package:
  - changed-files:
      - any-glob-to-any-file:
        - package.json
        - pnpm-lock.yaml
👗static:
  - changed-files:
      - any-glob-to-any-file:
        - static/*
🐙github:
  - changed-files:
      - any-glob-to-any-file:
        - .github/*
📄docs:
  - changed-files:
      - any-glob-to-any-file:
        - README.md
        - LICENSE

# 細かい分類
✈ci:
  - changed-files:
      - any-glob-to-any-file:
        - .github/workflows/*
        - .github/labeler.yml
🖼layout:
  - changed-files:
      - any-glob-to-any-file:
        - src/routes/**/+layout.svelte
        - src/app.css
🐟serverScript:
  - changed-files:
      - any-glob-to-any-file:
        - src/routes/**/+page.server.ts
        - src/lib/server/*
        - src/hooks.server.js
        - src/service-worker.js
📱clientScript:
  - changed-files:
      - any-glob-to-any-file:
        - src/hooks.client.js
