name = "usuyuki-portfolio-v6"
account_id = "override"

main = ".cloudflare/worker.js"
site.bucket = ".cloudflare/public"

build.command = "npm run build"

compatibility_date = "2023-03-15"
workers_dev = true

kv_namespaces = [
  { binding = "KV", id = "override", preview_id = "override" }
]
