name = "usuyuki-portfolio-v6-v2"
account_id = "override"

main = "dist/worker.js"
site.bucket = "dist/public"

build.command = "pnpm build"

compatibility_date = "2023-03-15"
workers_dev = true

kv_namespaces = [
  { binding = "KV", id = "override", preview_id = "override" }
]
