name = "usuyuki-portfolio-v6"
account_id = "ACCOUNT_ID"

main = ".cloudflare/worker.js"
site.bucket = ".cloudflare/public"

build.command = "pnpm build"

compatibility_date = "2023-03-18"
workers_dev = true

kv_namespaces = [
  { binding = "KV", id = "KV_ID", preview_id = "override" }
]
