name: 自動デプロイ 

on:
  pull_request:
    branches: [main]
# on:
#   push:
#     branches:
#       - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: .
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          preCommands: |
            corepack enable
            pnpm install
            touch .env
            echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" >> .env
            echo "GHOST_API_URL=${{ secrets.GHOST_API_URL }}" >> .env
            echo "GHOST_CONTENT_KEY=${{ secrets.GHOST_CONTENT_KEY }}" >> .env
            sed -i -e "s/\(account_id = \".*\)\(\"\)/\\1${{ secrets.CF_ACCOUNT_ID }}\2/" wrangler.toml'
            sed -i -e "s/\(id = \".*\)\(\"\)/\\1${{ secrets.CF_KV_ID }}\2/" wrangler.toml'
          command: |
            publish
            # --config指定しても効かないので注意
          env: |
            # NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
            # GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
            # GHOST_CONTENT_KEY: ${{ secrets.GHOST_CONTENT_KEY }}
            
            # 参考:https://developers.cloudflare.com/workers/wrangler/ci-cd/
