name: 自動デプロイ 

on:
  pull_request:
    branches: [main]
# on:
#   push:
#     branches:
#       - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: .
          preCommands: |
            corepack enable
            pnpm install
          command: publish --config wrangler-ci.toml 
          env: |
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
            CF_KV_NAMESPACES: ${{ secrets.CF_KV_NAMESPACES }}
            # 参考:https://developers.cloudflare.com/workers/wrangler/ci-cd/
