name: 自動デプロイ 

on:
  pull_request:
    branches: [main]
# on:
#   push:
#     branches:
#       - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: .
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          preCommands: |
            corepack enable
            pnpm install
            touch .env
            echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" >> .env
            echo "GHOST_API_URL=${{ secrets.GHOST_API_URL }}" >> .env
            echo "GHOST_CONTENT_KEY=${{ secrets.GHOST_CONTENT_KEY }}" >> .env
            ls -la
          command: |
            publish
            # --config指定しても効かないので注意
          env: |
            account_id: ${{ secrets.CF_ACCOUNT_ID }}
            # ↓{ binding = "KV", id = "override", preview_id = "override" }と文字列で入れる
            kv_namespaces: ${{ secrets.CF_KV_NAMESPACES }}
            NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
            GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
            GHOST_CONTENT_KEY: ${{ secrets.GHOST_CONTENT_KEY }}
            
            # 参考:https://developers.cloudflare.com/workers/wrangler/ci-cd/
